### ISSUE TITLE
Install prometheus custom resource in kubernetes cluster

### ISSUE THREAD

**Issue by limed** [mdn/infra#217]
Install the prometheus custom resource, this has potential to replace datadog at some point. Look into doing this and start experimenting with it. Helps resolves #52

**Comment by The-smooth-operator** [comment]
I started working in this one. Will be deploying the monitoring stack in Frankfurt an create a PR once everything is fine.
After we can look into deploying it in Oregon.

**Comment by The-smooth-operator** [comment]
Got good feedback from Ed: there's a duplication of kube-state-metrics.
If removing the one in monitoring namespace some of the community Grafana dashboard break because they are expecting kube-state-metrics to be there.
So, now I'm working in deploying the current one in monitoring namespace, while making sure I'm not breaking any Datadog graph

**Comment by limed** [comment]
Done in #227
