### ISSUE TITLE
Redis engine upgrade

### ISSUE THREAD

**Issue by limed** [mdn/infra#303]
Redis is running an older engine, look into what it would take to upgrade from its current engine to a newer engine

**Comment by peterbe** [comment]
I would wait until we have upgraded to Python 3 so we can upgrade our python redis library to the latest. 

What version are we currently using?

**Comment by limed** [comment]
We're currently running `3.2.4` and AWS supports up to version 5.x

**Comment by peterbe** [comment]
Plan:

1. Finish our upgrade to Python 3.
2. Review what the latest and greatest possible version of Redis we can use with `redis-py` and what the latest and greatest version of `django-redis` that can use that latest `redis-py`. 
3. Upgrade the Redis image used in `docker-compose.yml` and upgrade the python libs at the same time.
4. Once landed, orchestrate with @limed a timed upgrade so that we deploy at the same time as we upgrade our Redis server. 

One concern is the possible stampeding herd if it means we have to start with an empty new Redis so that all caches are cold all at once and overload as we warm up.
