### ISSUE TITLE
Redis instance class update

### ISSUE THREAD

**Issue by limed** [mdn/infra#304]
Once #303 is complete we need to look into updating redis to a newer instance class. Currently its running on `cache.m3.xlarge` and `cache.t3.small`, look into using a more modern instance class.

**Comment by escattone** [comment]
#### Summary
After discussing this with @limed, we can move ahead on this task, updating our stage and prod Redis instances to use the latest server class. This enables IT to then purchase and use reserved instances for Redis rather than the more expensive on-demand instances we're using now.

#### Plan
Do the following for both stage and prod:
1. Create new Redis instance (that uses reserve instances of the latest server class)
1. Put MDN into maintenance mode (for prod make sure this has been announced via a soapbox message at least 30 minutes prior)
1. Ensure Redis Celery queues have drained (`celery inspect active`)
1. Change the Redis URL's in the K8s secrets to point to the new Redis instance, and deploy (the new secrets will NOT be used until all of the deployments that use them are rolled)
1. Take MDN out of maintenance mode (which will "roll" all of the Kuma-image-based deployments, but not the Kumascript-image-based deployment) and also manually roll the `kumascript` deployment since it uses Redis as well. As the new pods are spun-up, they'll pick-up and use the new Redis URL's.

#### Acceptance Criteria
- [ ] Stage Redis instance updated to use reserved instances of the latest server class 
- [ ] Prod Redis instance updated to use reserved instances of the latest server class
