### ISSUE TITLE
Publish docker images from CI server

### ISSUE THREAD

**Issue by limed** [mdn/infra#33]
Moving issue from mozilla-itcloud/mdn-migration-project#15

**This is copy and pasted from repo listed above:**
Build docker images and push them to the repository from the CI server.  The MozMEAO Jenkins will continue building and pushing its own images. 

* MozMeao repository - https://quay.io/repository/mozmar
* IT Cloud repository - https://hub.docker.com/u/mdnwebdocs

| Image | MozMEAO name | IT Cloud name |
| -- | -- | -- |
| kuma_base | quay.io/mozmar/kuma_base | mdnwebdocs/kuma_base |
| kuma | quay.io/mozmar/kuma | mdnwebdocs/kuma |
| kumascript | quay.io/mozmar/kumascript | mdnwebdocs/kumascript |

Tasks:

* [x] Allow name to be configured from environment (devs)
* [x] Configure kuma pipeline to use IT Cloud name (IT)
* [x] Configure kumascript pipeline to use IT Cloud name (IT)
* [x] Determine credentials needed to push images (devs)
* [x] Provision and install push credentials on IT Cloud CI server (IT and devs)
* [x] Push kuma_base and kuma images from kuma pipeline (IT and devs)
* [x] Push kumascript images from kumascript pipeline (IT and devs)

**Comment by limed** [comment]
Note that there is a bunch of conversation that is missing from this issue, reference mozilla-itcloud/mdn-migration-project#15 for additional context

**Comment by jwhitlock** [comment]
It looks like this task is nearly complete.

It appears only the ``latest`` tag is pushed to ``kuma_base``:

https://hub.docker.com/r/mdnwebdocs/kuma_base/tags/

There appear to be more historical tags in quay.io:

https://quay.io/repository/mozmar/kuma_base?tab=tags

Maybe we only push a "latest" for kuma_base for master? I'll need to refresh my memory.

**Comment by jwhitlock** [comment]
Memory refreshed, thanks to @escattone. This task is done.

On the master branch, the ``latest`` tag  for ``kuma_base`` is built and pushed (see [Jenkinsfiles/master.groovy](https://github.com/mozilla/kuma/blob/master/Jenkinsfiles/master.groovy)).

On other branches, a tag based on the commit hash is build and pushed for ``kuma_base`` (see [Jenkinsfiles/default.groovy](https://github.com/mozilla/kuma/blob/master/Jenkinsfiles/default.groovy)).  We've gotten out of the habit of pushing branches to the mozilla/kuma repo, but instead use our forks, which aren't built in Jenkins.

For the ``kuma`` image, a commit-based tag is always used, which is why this repo just keeps growing. 

In practice, we only need to push ``kuma`` images that are going to production, but maybe we'll start pushing on every merge to master someday 😁
